k8s_config:
- manifest_path: /manifests/
  cluster_info:
    cluster_id: c2474c7f-c418-5d3b-9259-13bb5c1d5dfb
    cluster_name: acook pr demo cluster
- manifest_path: /manifests/
  cluster_info:
    cluster_id: c2474c7f-c418-5d3b-9259-13bb5c1d5dfb
    cluster_name: acook pr demo cluster
