apiVersion: v1
kind: Namespace
metadata:
  name: echo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: really-cool-app
  namespace: echo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: really-cool-app
  template:
    metadata:
      labels:
        app: really-cool-app
    spec:
      containers:
        - name: echo-server
          image: jmalloc/echo-server
          ports:
            - name: http-port
              containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: really-cool-app
  namespace: echo
spec:
  ports:
    - name: http-port
      port: 8081
      targetPort: http-port
      protocol: TCP
  selector:
    app: really-cool-app
---
apiVersion: x.getambassador.io/v3alpha1
kind: AmbassadorMapping
metadata:
  name: really-cool-app
  namespace: echo
spec:
  hostname: '*'
  prefix: /really-cool-app/
  service: really-cool-app

